### ISSUE TITLE
New child menus remain

### ISSUE THREAD

**Issue by vlimmerm** [bmaggi/library-training#28]
The new child menus are not adapted when creating a project in the UML or Library architecture context.
One would expect that the "Menu Library" is not visible when a UML project is created.

**Comment by bmaggi** [comment]
Thx, for the report!

I fixed that using a filter in the new child menu:
See 
https://github.com/bmaggi/library-training/blob/master/org.eclipse.papyrus.training.library.newchild/resources/newChild.creationmenumodel

<ElementCreationMenuModel:Folder xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ElementCreationMenuModel="http://www.eclipse.org/papyrus/infra/newchild/elementcreationmenumodel" xmlns:elementtypesconfigurations="http://www.eclipse.org/papyrus/infra/elementtypesconfigurations/1.2" xmlns:filters="http://www.eclipse.org/Papyrus/2014/common/filters" xmlns:umlfilters="http://www.eclipse.org/Papyrus/2014/uml/filters" xmi:id="org.eclipse.papyrus.training.library.menu" label="Menu Library" icon="platform:/plugin/org.eclipse.papyrus.training.library.profile/icons/library.gif">
  <filter filter="//@filter/@ownedFilter.0" xsi:type="filters:CompoundFilter">
    <ownedFilter name="isProfileApplied" profileQualifiedName="extlibrary" profileURI="pathmap://EXTLIBRARY_PROFILE/extlibrary.profile.uml#_LkNCUEomEeSz_ot9x6ZZgw" xsi:type="umlfilters:ProfileApplied"/>
  </filter>

Regards,
Benoit
