### ISSUE TITLE
The "new Relationship" menu remains hidden in UML architecture context

### ISSUE THREAD

**Issue by vlimmerm** [bmaggi/library-training#29]
Hello Benoit,

you hide the "new Relationship" menu in the /org.eclipse.papyrus.training.library.newchild activator.
But this menu remains hidden when one creates a UML project.

I wonder why the visibility / availabilty of a new child menu is not linked to the architecture context, in analogy with the palette?

Kind regards,

Marc

**Comment by bmaggi** [comment]
Hi,

1) The code in [HideNewChildEdgeUtil](https://github.com/bmaggi/library-training/blob/master/org.eclipse.papyrus.training.library.newchild/src/org/eclipse/papyrus/training/library/newchild/internal/HideNewChildEdgeUtil.java) is a _trick_ to hide the UML menu when creating an Enterprise Product. You may also hide the menus using the preferences, some people also used home made code to switch these preferences when changing viewpoints but nothing is currently integrated in Papyrus core.

2) Mostly for historic reason, most framework were created before the architecture one. 
Ideally, everything should be done using the architecture model, that's the golden goal but for the moment most of the frameworks work quite independently. 

=> Goal : New Child, Drop, Palette, css, assistant... should all be _ruled_ by the architecture model

/Benoit

**Comment by vlimmerm** [comment]
OK Benoit,

Thanks for the info.

Kind regards,

Marc

Marc Van Vlimmeren
Research engineer
Flanders Make vzw
Oude Diestersebaan 133
B-3920 Lommel

Tel.: +32 11 79 05 77
Mobile: +32 491 61 18 27
www.flandersmake.be<http://www.flandersmake.be/>
Volg ons op LinkedIn<https://www.linkedin.com/company/9277885>
