### ISSUE TITLE
Hide title of dependency if it's a borrows relationship

### ISSUE THREAD

**Issue by planger** [bmaggi/library-training#4]

**Comment by bmaggi** [comment]
What do you expect? 
Hiding Borrows1, Borrows2.... name in the diagram?

**Comment by planger** [comment]
Yes, exactly. When creating a new Borrows relationship, it gets and shows the default name, which seems to me unneeded. No big deal at all, but just wanted to mention it that I'd find it better to hide the name altogether in the diagram.

**Comment by bmaggi** [comment]
Done in the latest commit
