### ISSUE TITLE
Cannot create Borrower or Periodical from palette

### ISSUE THREAD

**Issue by planger** [bmaggi/library-training#5]
Creating a Borrower neither works in a library (package) nor outside a library. You can only create them by adding them in the model explorer and dropping them into the package.

**Comment by planger** [comment]
Same is true for Periodical.

**Comment by bmaggi** [comment]
Thx for catching it!

I couldn't create a Borrower or a Periodical in a <<Library>> Package from the Palette
but it was working fine directly on the diagram.

I fixed Borrower and Periodical creation from Palette in package
I added library in the palette.

**Comment by bmaggi** [comment]
Should work now.
